name: event_connect
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.0.0
  sqflite: ^2.0.0+3
  path_provider: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  floor_generator: ^1.0.0
  mockito: ^5.0.16 # Bu satırı ekleyin

flutter:
  uses-material-design: true
